/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseForm: typeof import('./components/base/BaseForm.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    ConfirmDeleteModal: typeof import('./components/ConfirmDeleteModal.vue')['default']
    CreateTaskModal: typeof import('./components/CreateTaskModal.vue')['default']
    EditTaskModal: typeof import('./components/EditTaskModal.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
  }
}
